name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip

      - name: cat NR
        id: output_result
        run: |
              cat ${{github.workspace}}/NR;
              echo "::set-output name=pull_request_number::$(cat ${{github.workspace}}/NR)";

      - name: Find Comment
        continue-on-error: true
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.output_result.outputs.pull_request_number }}
          comment-author: 'github-actions[bot]'


      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.output_result.outputs.pull_request_number }}
          # If the comment-id is blank, this will create a new comment.
          # Otherwise, it will update the comment.
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          body: |
            Create or update this comment.
          edit-mode: replace
        if: success()


